language: python
services:
 - mongodb
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
 - REPO=`pwd`
 - echo $REPO
 - pwd
 - "sudo apt-get -qq update"
 - "sudo apt-get -qq install python-dev libevent-dev"
 - "sudo apt-get -qq install libatlas-dev libatlas-base-dev gfortran"
 - "sudo apt-get -qq install python-numpy python-numpy-dev python-scipy"
# Dependencies for the php sandbox
 - "sudo apt-get -qq install php5 php5-dev"
# Install hpfeeds
 - cd /tmp
 - git clone git://github.com/rep/hpfeeds.git hpfeeds
 - cd hpfeeds
 - sudo python setup.py install
# Install Better Function Replacer (BFR)
 - cd /tmp
 - git clone git://github.com/glastopf/BFR.git
 - cd BFR
 - phpize
 - ./configure --enable-bfr
 - make
 - sudo make install
# TODO: Extract path from output
 - sudo bash -c 'echo "zend_extension = /usr/lib/php5/20090626/bfr.so" >> /etc/php5/cli/php.ini'
 - php5 --version
 - cd $REPO
 - cd glastopf
 - cd sandbox
 - sudo make
 - pwd
# Clone libinjection
 - cd /opt
 - sudo git clone git://github.com/client9/libinjection.git
install:
 - export PYTHONIOENCODING=UTF8 # just in case
 - pwd
 - cd $REPO
 - pip install cython
 - pip install -r requirements.txt --use-mirrors
# command to run tests
script: 
 - echo $REPO
 - pwd
 - nosetests
notifications:
 irc:
  - "irc.freenode.org#glastopf"
